'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MitgliedEntity
    Public Property mitIdPk As Integer
    Public Property mitName As String
    Public Property mitVorname As String
    Public Property mitStraßeNr As String
    Public Property mitPlzOrt As String
    Public Property mitTel As String
    Public Property mitEmail As String
    Public Property mitGebDatum As Nullable(Of Date)
    Public Property mitMtglDatum As Nullable(Of Date)
    Public Property mitVersion As Byte()

    Public Overridable Property tblTrainingseinheiten As ICollection(Of TrainingseinheitEntity) = New HashSet(Of TrainingseinheitEntity)

End Class
