'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TrainingseinheitEntity
    Public Property trainIdPk As Integer
    Public Property trainMitIdFk As Nullable(Of Integer)
    Public Property trainBenIdFk As Nullable(Of Integer)
    Public Property trainDatum As Nullable(Of Date)
    Public Property trainVersion As Byte()

    Public Overridable Property tblBenutzer As BenutzerEntity
    Public Overridable Property tblMitglieder As MitgliedEntity

End Class
